#!/usr/bin/env bash
# Generate CloudScope runtime build metadata before packaging.
#
# This script writes src/cloudscope/_build_info.py so the packaged .app can show
# the exact source identity it was built from. The generated file is transient
# and should not be committed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/_config.sh"

mkdir -p "$(dirname "$BUILD_INFO_PATH")"

APP_VERSION="$(grep -E '^version[[:space:]]*=' "$REPO_ROOT/pyproject.toml" 2>/dev/null | head -1 | sed -E 's/^version[[:space:]]*=[[:space:]]*["'\'' ]*([^"'\'' ]+)["'\'' ]*.*/\1/')"
APP_VERSION="${APP_VERSION:-0.0.0}"

GIT_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
GIT_COMMIT_SHORT="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
GIT_BRANCH="$(git -C "$REPO_ROOT" symbolic-ref --short -q HEAD 2>/dev/null || echo detached)"
GIT_TAG="$(git -C "$REPO_ROOT" describe --tags --exact-match HEAD 2>/dev/null || true)"
if [[ -z "$GIT_TAG" ]]; then
  GIT_TAG=""
fi

if [[ -n "$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null)" ]]; then
  GIT_STATE="dirty"
else
  GIT_STATE="clean"
fi

BUILD_TIMESTAMP_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BUILD_TIMESTAMP_LOCAL="$(date +%Y-%m-%dT%H:%M:%S%z)"
BUILD_BUNDLE_VERSION="${BUILD_BUNDLE_VERSION:-$APP_VERSION}"
PYTHON_VERSION="$(python - <<'PY'
import sys
print(sys.version.split()[0])
PY
)"
NICEGUI_VERSION="$(python - <<'PY'
from importlib import metadata
try:
    print(metadata.version('nicegui'))
except metadata.PackageNotFoundError:
    print('unknown')
PY
)"
PYINSTALLER_VERSION="$(python - <<'PY'
from importlib import metadata
try:
    print(metadata.version('pyinstaller'))
except metadata.PackageNotFoundError:
    print('unknown')
PY
)"
PLATFORM_VALUE="$(python - <<'PY'
import platform
print(platform.platform())
PY
)"

cat > "$BUILD_INFO_PATH" <<PY
"""Auto-generated build metadata.

Generated by packaging/macos/build_info.sh. Do not edit or commit this file.
"""

BUILD_INFO = {
    'app_name': '$APP_NAME',
    'version': '$APP_VERSION',
    'git_tag': ${GIT_TAG:+"'$GIT_TAG'"}${GIT_TAG:-None},
    'git_commit': '$GIT_COMMIT',
    'git_commit_short': '$GIT_COMMIT_SHORT',
    'git_branch': '$GIT_BRANCH',
    'git_state': '$GIT_STATE',
    'build_timestamp_utc': '$BUILD_TIMESTAMP_UTC',
    'build_timestamp_local': '$BUILD_TIMESTAMP_LOCAL',
    'build_bundle_version': '$BUILD_BUNDLE_VERSION',
    'python_version': '$PYTHON_VERSION',
    'nicegui_version': '$NICEGUI_VERSION',
    'pyinstaller_version': '$PYINSTALLER_VERSION',
    'platform': '$PLATFORM_VALUE',
}
PY

PYTHONPATH="$REPO_ROOT/src" python - <<'PY'
import json
from pathlib import Path
from cloudscope import _build_info
import os
path = Path(os.environ['BUILD_INFO_JSON_PATH'])
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(json.dumps(_build_info.BUILD_INFO, indent=2) + "\n")
print(f"[build-info] Wrote {path}")
PY

echo "[build-info] Wrote $BUILD_INFO_PATH"
echo "[build-info] Version : $APP_VERSION"
echo "[build-info] Commit  : $GIT_COMMIT_SHORT"
echo "[build-info] Tag     : ${GIT_TAG:-none}"
echo "[build-info] State   : $GIT_STATE"
