#!/usr/bin/env bash
# Write a tiny build-info module into src/cloudscope/ so it can be bundled.
# This file is removed by build_app.sh after nicegui-pack completes.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/_config.sh"

mkdir -p "$(dirname "$BUILD_INFO_PATH")"

GIT_SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
GIT_BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
BUILD_TIME_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
APP_VERSION="$(grep -E '^version[[:space:]]*=' "$REPO_ROOT/pyproject.toml" 2>/dev/null | head -1 | sed -E 's/^version[[:space:]]*=[[:space:]]*["'\'' ]*([^"'\'' ]+)["'\'' ]*.*/\1/')"
APP_VERSION="${APP_VERSION:-0.0.0}"

cat > "$BUILD_INFO_PATH" <<PY
"""Build metadata generated by packaging/macos/build_info.sh."""

APP_NAME = "$APP_NAME"
APP_VERSION = "$APP_VERSION"
GIT_SHA = "$GIT_SHA"
GIT_BRANCH = "$GIT_BRANCH"
BUILD_TIME_UTC = "$BUILD_TIME_UTC"
PY

echo "[build-info] Wrote $BUILD_INFO_PATH"
