"""Runtime access to CloudScope build metadata.

The macOS packaging pipeline generates ``cloudscope._build_info`` immediately
before bundling the app.  Development runs usually do not have that generated
module, so this module provides a stable, importable API with sensible fallback
values.
"""

from __future__ import annotations

import platform
import sys
from dataclasses import dataclass
from importlib import metadata
from typing import Any


@dataclass(frozen=True, slots=True)
class BuildInfo:
    """Application build metadata shown in the runtime UI.

    Args:
        app_name: Human-readable application name.
        version: Application version from ``pyproject.toml`` or package metadata.
        git_tag: Exact git tag used for release builds, if available.
        git_commit: Git commit hash used for the build, or ``"unknown"``.
        git_branch: Git branch or ``"detached"`` when built from a tag checkout.
        git_state: ``"clean"`` or ``"dirty"`` when known.
        build_timestamp_utc: UTC timestamp generated by the build pipeline.
        build_timestamp_local: Local timestamp generated by the build pipeline.
        build_bundle_version: macOS ``CFBundleVersion`` value used for the app.
        python_version: Python version used during packaging/runtime fallback.
        nicegui_version: NiceGUI version used during packaging/runtime fallback.
        pyinstaller_version: PyInstaller version used during packaging, if known.
        platform: Platform string from the build machine or runtime fallback.
    """

    app_name: str
    version: str
    git_tag: str | None
    git_commit: str
    git_branch: str
    git_state: str
    build_timestamp_utc: str
    build_timestamp_local: str
    build_bundle_version: str
    python_version: str
    nicegui_version: str
    pyinstaller_version: str
    platform: str


def _package_version(package_name: str, default: str = 'unknown') -> str:
    """Return an installed package version.

    Args:
        package_name: Distribution package name.
        default: Value returned when the package metadata is unavailable.

    Returns:
        Installed package version or ``default``.
    """
    try:
        return metadata.version(package_name)
    except metadata.PackageNotFoundError:
        return default


def _load_generated_build_info() -> dict[str, Any]:
    """Load generated build metadata when present.

    Returns:
        Build metadata dictionary generated by ``packaging/macos/build_info.sh``.
        Returns an empty dictionary during normal development runs.
    """
    try:
        from cloudscope._build_info import BUILD_INFO  # type: ignore[import-not-found]
    except Exception:
        return {}
    if not isinstance(BUILD_INFO, dict):
        return {}
    return dict(BUILD_INFO)


def get_build_info() -> BuildInfo:
    """Return runtime build metadata.

    Returns:
        Build metadata from the generated packaging module when available, or
        development fallback metadata when running from source.
    """
    generated = _load_generated_build_info()
    version = str(generated.get('version') or _package_version('cloudscope', default='dev'))
    return BuildInfo(
        app_name=str(generated.get('app_name') or 'CloudScope'),
        version=version,
        git_tag=generated.get('git_tag'),
        git_commit=str(generated.get('git_commit') or 'unknown'),
        git_branch=str(generated.get('git_branch') or 'unknown'),
        git_state=str(generated.get('git_state') or 'unknown'),
        build_timestamp_utc=str(generated.get('build_timestamp_utc') or 'development'),
        build_timestamp_local=str(generated.get('build_timestamp_local') or 'development'),
        build_bundle_version=str(generated.get('build_bundle_version') or version),
        python_version=str(generated.get('python_version') or sys.version.split()[0]),
        nicegui_version=str(generated.get('nicegui_version') or _package_version('nicegui')),
        pyinstaller_version=str(generated.get('pyinstaller_version') or _package_version('pyinstaller')),
        platform=str(generated.get('platform') or platform.platform()),
    )


def get_build_info_rows() -> tuple[tuple[str, str], ...]:
    """Return build metadata as display rows.

    Returns:
        Tuple of ``(label, value)`` pairs suitable for display in a simple UI.
    """
    info = get_build_info()
    git_tag = info.git_tag if info.git_tag else 'not tagged'
    return (
        ('App', info.app_name),
        ('Version', info.version),
        ('Git tag', git_tag),
        ('Git commit', info.git_commit),
        ('Git branch', info.git_branch),
        ('Git state', info.git_state),
        ('Built UTC', info.build_timestamp_utc),
        ('Built local', info.build_timestamp_local),
        ('Bundle version', info.build_bundle_version),
        ('Python', info.python_version),
        ('NiceGUI', info.nicegui_version),
        ('PyInstaller', info.pyinstaller_version),
        ('Platform', info.platform),
    )
